name: Windows Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build solution
      run: |
        msbuild Terminator.sln /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Terminator-exe
        path: '**/Release/*.exe'
